"""empty message

Revision ID: 9858d0f8eae2
Revises: 9a7da5e88c32
Create Date: 2025-12-04 12:49:51.384880

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '9858d0f8eae2'
down_revision = '9a7da5e88c32'
branch_labels = None
depends_on = None


def upgrade():
    # If the initial schema is already present (embedding table exists), skip to avoid duplicate creation.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('embedding'):
        return

    # Ensure pgvector extension is available before creating Vector columns.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.Enum('article_translation', 'transcript', 'tag', name='embedding_owner_type'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector', Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.create_index('idx_embedding_language', ['language'], unique=False)
        batch_op.create_index('idx_embedding_owner', ['owner_type', 'owner_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('default_label', sa.String(length=200), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('article', 'video', 'audio', name='content_type'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'org', 'public', name='visibility_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_label',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'language', name='uq_tag_language')
    )
    with op.batch_alter_table('tag_label', schema=None) as batch_op:
        batch_op.create_index('idx_tag_label_language', ['language'], unique=False)

    op.create_table('webhook_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='webhook_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_event_status', ['status'], unique=False)
        batch_op.create_index('idx_webhook_event_type', ['event_type'], unique=False)

    op.create_table('article_translation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=600), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'language', name='uq_content_language'),
    sa.UniqueConstraint('slug', 'language', name='uq_slug_language')
    )
    with op.batch_alter_table('article_translation', schema=None) as batch_op:
        batch_op.create_index('idx_article_language', ['language'], unique=False)
        batch_op.create_index('idx_article_slug', ['slug'], unique=False)

    op.create_table('content_tag',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_table('media_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('video', 'audio', name='media_kind'), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_table('transcript',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'language', name='uq_media_language')
    )
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.create_index('idx_transcript_language', ['language'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_index('idx_transcript_language')

    op.drop_table('transcript')
    op.drop_table('media_content')
    op.drop_table('content_tag')
    with op.batch_alter_table('article_translation', schema=None) as batch_op:
        batch_op.drop_index('idx_article_slug')
        batch_op.drop_index('idx_article_language')

    op.drop_table('article_translation')
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_index('idx_webhook_event_type')
        batch_op.drop_index('idx_webhook_event_status')

    op.drop_table('webhook_event')
    with op.batch_alter_table('tag_label', schema=None) as batch_op:
        batch_op.drop_index('idx_tag_label_language')

    op.drop_table('tag_label')
    op.drop_table('content')
    op.drop_table('webhook')
    op.drop_table('user')
    op.drop_table('tag')
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.drop_index('idx_embedding_owner')
        batch_op.drop_index('idx_embedding_language')

    op.drop_table('embedding')
    # ### end Alembic commands ###
